gui:
  # Enable Vim-like keybindings (hjkl, etc.)
  useCtrlKeys: true
  nerdFontsVersion: 3   # optional: better icons
  showCommandLog: true
  theme:
    activeBorderColor:
      - "#83a598"   # deus blue
      - bold
    inactiveBorderColor:
      - "#665c54"
    optionsTextColor:
      - "#8ec07c"
    selectedLineBgColor:
      - "#35312f"
    selectedLineFgColor:
      - "#ebdbb2"
    cherryPickedCommitTextStyle:
      - "#d5508f"
    markedBaseCommitTextStyle:
      - "#fe8019"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"

keybinding:
  universal:
    quit: "q"
    return: "<esc>"   # makes Esc behave like leaving a mode
  files:
    nextItem: "j"
    prevItem: "k"
    toggleStaged: "space"
